sudo: false
language: node_js
services:
  - postgres
addons:
  postgresql: "9.4"
node_js:
  - "4"
before_script:
  - psql -c 'create database oauth2_server;' -U postgres
after_success: npm run coverage
